import { z } from "zod";

export const departmentDbResponseSchema = z.object({
  id: z.string(),
  organizationId: z.string(),
  odooDepartmentId: z.number().nullable().optional(),
  name: z.string(),
  code: z.string().nullable().optional(),
  parentId: z.string().nullable().optional(),
  managerId: z.string().nullable().optional(),
  color: z.number().nullable().optional(),
  note: z.string().nullable().optional(),
  lastSyncedAt: z.string().nullable().optional(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export type DepartmentDbResponse = z.infer<typeof departmentDbResponseSchema>;

export const employeeDbResponseSchema = z.object({
  id: z.string(),
  organizationId: z.string(),
  userId: z.string().nullable().optional(),
  odooEmployeeId: z.number().nullable().optional(),
  name: z.string(),
  email: z.string().nullable().optional(),
  phone: z.string().nullable().optional(),
  mobile: z.string().nullable().optional(),
  workEmail: z.string().nullable().optional(),
  workPhone: z.string().nullable().optional(),
  workLocation: z.string().nullable().optional(),
  jobTitle: z.string().nullable().optional(),
  departmentId: z.string().nullable().optional(),
  managerId: z.string().nullable().optional(),
  employeeType: z.enum(["employee", "student", "trainee", "contractor", "freelance"]).nullable().optional(),
  gender: z.enum(["male", "female", "other"]).nullable().optional(),
  maritalStatus: z.enum(["single", "married", "cohabitant", "widower", "divorced"]).nullable().optional(),
  birthday: z.string().nullable().optional(),
  placeOfBirth: z.string().nullable().optional(),
  countryOfBirth: z.string().nullable().optional(),
  nationality: z.string().nullable().optional(),
  identificationId: z.string().nullable().optional(),
  passportId: z.string().nullable().optional(),
  bankAccountNumber: z.string().nullable().optional(),
  bankName: z.string().nullable().optional(),
  bankIban: z.string().nullable().optional(),
  emergencyContact: z.string().nullable().optional(),
  emergencyPhone: z.string().nullable().optional(),
  emergencyRelation: z.string().nullable().optional(),
  hireDate: z.string().nullable().optional(),
  terminationDate: z.string().nullable().optional(),
  photoUrl: z.string().nullable().optional(),
  notes: z.string().nullable().optional(),
  active: z.boolean(),
  lastSyncedAt: z.string().nullable().optional(),
  createdAt: z.string(),
  updatedAt: z.string(),
  countryId: z.string().nullable().optional(),
  identificationType: z.string().nullable().optional(),
  identificationNumber: z.string().nullable().optional(),
  passportNumber: z.string().nullable().optional(),
  certificateLevel: z.string().nullable().optional(),
  fieldOfStudy: z.string().nullable().optional(),
  school: z.string().nullable().optional(),
  visa: z.string().nullable().optional(),
  workPermit: z.string().nullable().optional(),
  visaExpire: z.string().nullable().optional(),
  workPermitExpire: z.string().nullable().optional(),
});

export type EmployeeDbResponse = z.infer<typeof employeeDbResponseSchema>;

