"use client";

import React from "react";
import {
  InvoicePDF,
  TablePDF,
  PDFDownloadButton,
  ExcelPreview,
  simpleExportToExcel,
  exportToExcel,
  exportWithConditionalFormatting,
  generatePDFBlob,
  type InvoiceData,
  type TablePDFData,
  type ExcelColumn,
} from "@safee/ui";

// Sample data
const sampleInvoices = [
  {
    invoiceNumber: "INV-001",
    client: "Acme Corporation",
    amount: 5000,
    status: "Paid",
    date: "2024-11-01",
  },
  {
    invoiceNumber: "INV-002",
    client: "Tech Innovators Ltd",
    amount: 3500,
    status: "Pending",
    date: "2024-11-05",
  },
  {
    invoiceNumber: "INV-003",
    client: "Global Solutions Inc",
    amount: 7200,
    status: "Paid",
    date: "2024-11-10",
  },
  {
    invoiceNumber: "INV-004",
    client: "Digital Ventures",
    amount: 2800,
    status: "Overdue",
    date: "2024-10-15",
  },
  {
    invoiceNumber: "INV-005",
    client: "Smart Systems LLC",
    amount: 4500,
    status: "Pending",
    date: "2024-11-12",
  },
];

const sampleInvoiceData: InvoiceData = {
  invoiceNumber: "INV-2024-001",
  date: "2024-11-17",
  dueDate: "2024-12-17",

  companyName: "Safee Analytics",
  companyAddress: "Business Bay, Dubai, UAE",
  companyPhone: "+971 4 123 4567",
  companyEmail: "billing@safee.com",

  clientName: "Acme Corporation",
  clientAddress: "Downtown, Abu Dhabi, UAE",
  clientEmail: "accounts@acme.com",
  clientPhone: "+971 2 987 6543",

  items: [
    {
      description: "Hisabiq Accounting Module - Monthly Subscription",
      quantity: 1,
      unitPrice: 999,
      total: 999,
    },
    {
      description: "Kanz HR Module - Monthly Subscription",
      quantity: 1,
      unitPrice: 799,
      total: 799,
    },
    {
      description: "Nisbah CRM Module - Monthly Subscription",
      quantity: 1,
      unitPrice: 699,
      total: 699,
    },
    {
      description: "Additional User Licenses",
      quantity: 10,
      unitPrice: 50,
      total: 500,
    },
  ],

  subtotal: 2997,
  taxRate: 5,
  taxAmount: 149.85,
  total: 3146.85,

  currency: "AED",
  notes:
    "Payment is due within 30 days. Please include invoice number in payment reference. Thank you for your business!",
};

const salesReportData: TablePDFData = {
  title: "Monthly Sales Report",
  subtitle: "November 2024",
  orientation: "landscape",
  columns: [
    { header: "Date", key: "date", width: 1, align: "left" },
    { header: "Invoice #", key: "invoiceNumber", width: 1.2 },
    { header: "Client", key: "client", width: 2 },
    {
      header: "Amount (AED)",
      key: "amount",
      width: 1.2,
      align: "right",
      format: (value) => `${value.toLocaleString()}`,
    },
    { header: "Status", key: "status", width: 1, align: "center" },
  ],
  data: sampleInvoices,
  footer: "Generated by Safee Analytics | Confidential",
};

const excelColumns: ExcelColumn[] = [
  { header: "Invoice Number", key: "invoiceNumber", width: 15 },
  { header: "Client Name", key: "client", width: 25 },
  {
    header: "Amount (AED)",
    key: "amount",
    width: 15,
  },
  { header: "Status", key: "status", width: 12 },
  { header: "Date", key: "date", width: 15 },
];

export default function ExportsDemo() {
  const [loading, setLoading] = React.useState<string | null>(null);
  const [invoicePdfUrl, setInvoicePdfUrl] = React.useState<string | null>(null);
  const [reportPdfUrl, setReportPdfUrl] = React.useState<string | null>(null);

  // Generate PDF preview URLs
  React.useEffect(() => {
    const generatePreviews = async () => {
      try {
        const invoiceBlob = await generatePDFBlob(
          <InvoicePDF invoice={sampleInvoiceData} />
        );
        const invoiceUrl = URL.createObjectURL(invoiceBlob);
        setInvoicePdfUrl(invoiceUrl);

        const reportBlob = await generatePDFBlob(
          <TablePDF data={salesReportData} />
        );
        const reportUrl = URL.createObjectURL(reportBlob);
        setReportPdfUrl(reportUrl);
      } catch (error) {
        console.error("Error generating PDF previews:", error);
      }
    };

    generatePreviews();

    // Cleanup URLs on unmount
    return () => {
      if (invoicePdfUrl) URL.revokeObjectURL(invoicePdfUrl);
      if (reportPdfUrl) URL.revokeObjectURL(reportPdfUrl);
    };
  }, [invoicePdfUrl, reportPdfUrl]);

  // Excel Export Handlers
  const handleSimpleExcelExport = async () => {
    setLoading("simple-excel");
    try {
      await simpleExportToExcel(sampleInvoices, "invoices-simple");
    } finally {
      setLoading(null);
    }
  };

  const handleAdvancedExcelExport = async () => {
    setLoading("advanced-excel");
    try {
      await exportToExcel({
        filename: "invoices-advanced",
        sheetName: "Invoices",
        columns: excelColumns,
        data: sampleInvoices,
        autoFilter: true,
        freezeHeader: true,
      });
    } finally {
      setLoading(null);
    }
  };

  const handleConditionalExcelExport = async () => {
    setLoading("conditional-excel");
    try {
      await exportWithConditionalFormatting({
        filename: "invoices-conditional",
        columns: excelColumns,
        data: sampleInvoices,
        conditionalRules: [
          {
            column: "status",
            condition: (value) => value === "Paid",
            style: {
              fill: {
                type: "pattern",
                pattern: "solid",
                fgColor: { argb: "FF00FF00" },
              },
              font: { bold: true },
            },
          },
          {
            column: "status",
            condition: (value) => value === "Overdue",
            style: {
              fill: {
                type: "pattern",
                pattern: "solid",
                fgColor: { argb: "FFFF0000" },
              },
              font: { color: { argb: "FFFFFFFF" }, bold: true },
            },
          },
        ],
      });
    } finally {
      setLoading(null);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 via-blue-50 to-purple-50 p-6">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="mb-8 text-center">
          <h1 className="text-4xl font-bold mb-3 bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
            Export Library Showcase
          </h1>
          <p className="text-gray-600 text-lg">
            Professional Excel & PDF exports with live previews • Zero cost • Full control
          </p>
          <div className="mt-4 inline-flex items-center gap-2 px-4 py-2 bg-green-100 border border-green-300 rounded-full text-green-800 text-sm font-medium">
            <span>💰</span>
            <span>Saves $1,199/dev/year vs KendoReact</span>
          </div>
        </div>

        {/* Main Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Excel Export Card */}
          <div className="bg-white rounded-xl shadow-lg border border-gray-200 overflow-hidden">
            <div className="bg-gradient-to-r from-green-500 to-emerald-500 p-6 text-white">
              <h2 className="text-2xl font-bold flex items-center gap-3">
                <span className="text-3xl">📊</span>
                Excel Exports
              </h2>
              <p className="mt-2 text-green-50">
                Advanced spreadsheet generation with formatting
              </p>
            </div>

            <div className="p-6">
              {/* Preview */}
              <div className="mb-6">
                <h3 className="text-sm font-semibold text-gray-700 mb-3 uppercase tracking-wide">
                  Live Preview
                </h3>
                <div className="rounded-lg overflow-hidden border-2 border-gray-200">
                  <ExcelPreview
                    columns={excelColumns}
                    data={sampleInvoices}
                    maxRows={5}
                  />
                </div>
              </div>

              {/* Export Options */}
              <div className="space-y-3">
                <h3 className="text-sm font-semibold text-gray-700 mb-3 uppercase tracking-wide">
                  Export Options
                </h3>

                <button
                  onClick={handleSimpleExcelExport}
                  disabled={loading === "simple-excel"}
                  className="w-full flex items-center justify-between px-4 py-3 bg-green-50 border-2 border-green-200 rounded-lg hover:bg-green-100 hover:border-green-300 transition disabled:opacity-50 group"
                >
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 bg-green-500 rounded-lg flex items-center justify-center text-white font-bold">
                      1
                    </div>
                    <div className="text-left">
                      <div className="font-semibold text-gray-900">Simple Export</div>
                      <div className="text-xs text-gray-600">Auto-generated columns</div>
                    </div>
                  </div>
                  <svg className="w-5 h-5 text-green-600 group-hover:translate-x-1 transition" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
                  </svg>
                </button>

                <button
                  onClick={handleAdvancedExcelExport}
                  disabled={loading === "advanced-excel"}
                  className="w-full flex items-center justify-between px-4 py-3 bg-blue-50 border-2 border-blue-200 rounded-lg hover:bg-blue-100 hover:border-blue-300 transition disabled:opacity-50 group"
                >
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 bg-blue-500 rounded-lg flex items-center justify-center text-white font-bold">
                      2
                    </div>
                    <div className="text-left">
                      <div className="font-semibold text-gray-900">Advanced Export</div>
                      <div className="text-xs text-gray-600">Filters & formatting</div>
                    </div>
                  </div>
                  <svg className="w-5 h-5 text-blue-600 group-hover:translate-x-1 transition" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
                  </svg>
                </button>

                <button
                  onClick={handleConditionalExcelExport}
                  disabled={loading === "conditional-excel"}
                  className="w-full flex items-center justify-between px-4 py-3 bg-purple-50 border-2 border-purple-200 rounded-lg hover:bg-purple-100 hover:border-purple-300 transition disabled:opacity-50 group"
                >
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 bg-purple-500 rounded-lg flex items-center justify-center text-white font-bold">
                      3
                    </div>
                    <div className="text-left">
                      <div className="font-semibold text-gray-900">Conditional Formatting</div>
                      <div className="text-xs text-gray-600">Status-based colors</div>
                    </div>
                  </div>
                  <svg className="w-5 h-5 text-purple-600 group-hover:translate-x-1 transition" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
                  </svg>
                </button>
              </div>

              {/* Features */}
              <div className="mt-6 p-4 bg-gray-50 rounded-lg">
                <h4 className="text-xs font-semibold text-gray-700 mb-2 uppercase">Features</h4>
                <div className="grid grid-cols-2 gap-2 text-xs text-gray-600">
                  <div className="flex items-center gap-1">
                    <span className="text-green-500">✓</span>
                    <span>Auto-filters</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <span className="text-green-500">✓</span>
                    <span>Frozen headers</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <span className="text-green-500">✓</span>
                    <span>Cell formatting</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <span className="text-green-500">✓</span>
                    <span>Import support</span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* PDF Export Card */}
          <div className="bg-white rounded-xl shadow-lg border border-gray-200 overflow-hidden">
            <div className="bg-gradient-to-r from-blue-500 to-indigo-500 p-6 text-white">
              <h2 className="text-2xl font-bold flex items-center gap-3">
                <span className="text-3xl">📄</span>
                PDF Documents
              </h2>
              <p className="mt-2 text-blue-50">
                Professional invoices and reports
              </p>
            </div>

            <div className="p-6 space-y-6">
              {/* Invoice */}
              <div className="border-2 border-gray-200 rounded-lg overflow-hidden hover:border-blue-300 transition">
                <div className="bg-gray-50 p-3 border-b border-gray-200">
                  <div className="flex items-center justify-between">
                    <h3 className="font-semibold text-gray-900">Professional Invoice</h3>
                    <span className="px-2 py-1 bg-blue-100 text-blue-700 text-xs font-medium rounded">
                      Template
                    </span>
                  </div>
                </div>

                {/* Invoice Preview Frame */}
                <div className="relative bg-white" style={{ height: "400px" }}>
                  {invoicePdfUrl ? (
                    <iframe
                      src={`${invoicePdfUrl}#toolbar=0&navpanes=0&scrollbar=0`}
                      className="w-full h-full"
                      title="Invoice Preview"
                    />
                  ) : (
                    <div className="flex items-center justify-center h-full">
                      <div className="text-center">
                        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500 mx-auto mb-3"></div>
                        <p className="text-gray-500 text-sm">Generating preview...</p>
                      </div>
                    </div>
                  )}
                </div>

                <div className="p-4 bg-gray-50 border-t border-gray-200">
                  <div className="grid grid-cols-3 gap-2 text-xs mb-3">
                    <div>
                      <span className="text-gray-500">Invoice:</span>
                      <span className="font-medium ml-1">{sampleInvoiceData.invoiceNumber}</span>
                    </div>
                    <div>
                      <span className="text-gray-500">Client:</span>
                      <span className="font-medium ml-1 truncate">{sampleInvoiceData.clientName}</span>
                    </div>
                    <div>
                      <span className="text-gray-500">Total:</span>
                      <span className="font-medium ml-1">{sampleInvoiceData.currency} {sampleInvoiceData.total.toLocaleString()}</span>
                    </div>
                  </div>

                  <PDFDownloadButton
                    document={<InvoicePDF invoice={sampleInvoiceData} />}
                    fileName={`invoice-${sampleInvoiceData.invoiceNumber}`}
                    className="w-full px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition font-medium"
                  >
                    Download Invoice PDF
                  </PDFDownloadButton>
                </div>
              </div>

              {/* Report */}
              <div className="border-2 border-gray-200 rounded-lg overflow-hidden hover:border-indigo-300 transition">
                <div className="bg-gray-50 p-3 border-b border-gray-200">
                  <div className="flex items-center justify-between">
                    <h3 className="font-semibold text-gray-900">Sales Report</h3>
                    <span className="px-2 py-1 bg-indigo-100 text-indigo-700 text-xs font-medium rounded">
                      Landscape
                    </span>
                  </div>
                </div>

                {/* Report Preview Frame */}
                <div className="relative bg-white" style={{ height: "300px" }}>
                  {reportPdfUrl ? (
                    <iframe
                      src={`${reportPdfUrl}#toolbar=0&navpanes=0&scrollbar=0`}
                      className="w-full h-full"
                      title="Report Preview"
                    />
                  ) : (
                    <div className="flex items-center justify-center h-full">
                      <div className="text-center">
                        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-500 mx-auto mb-3"></div>
                        <p className="text-gray-500 text-sm">Generating preview...</p>
                      </div>
                    </div>
                  )}
                </div>

                <div className="p-4 bg-gray-50 border-t border-gray-200">
                  <div className="grid grid-cols-2 gap-2 text-xs mb-3">
                    <div>
                      <span className="text-gray-500">Period:</span>
                      <span className="font-medium ml-1">{salesReportData.subtitle}</span>
                    </div>
                    <div>
                      <span className="text-gray-500">Records:</span>
                      <span className="font-medium ml-1">{salesReportData.data.length} invoices</span>
                    </div>
                  </div>

                  <PDFDownloadButton
                    document={<TablePDF data={salesReportData} />}
                    fileName="sales-report-november-2024"
                    className="w-full px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition font-medium"
                  >
                    Download Report PDF
                  </PDFDownloadButton>
                </div>
              </div>

              {/* Features */}
              <div className="p-4 bg-gray-50 rounded-lg">
                <h4 className="text-xs font-semibold text-gray-700 mb-2 uppercase">Features</h4>
                <div className="grid grid-cols-2 gap-2 text-xs text-gray-600">
                  <div className="flex items-center gap-1">
                    <span className="text-blue-500">✓</span>
                    <span>Custom templates</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <span className="text-blue-500">✓</span>
                    <span>Page numbers</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <span className="text-blue-500">✓</span>
                    <span>Branding</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <span className="text-blue-500">✓</span>
                    <span>Multi-page</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Bottom Stats */}
        <div className="mt-8 grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="bg-white rounded-xl shadow-md p-6 text-center border border-gray-200">
            <div className="text-3xl font-bold text-green-600 mb-2">$0</div>
            <div className="text-gray-600 text-sm">Total Cost</div>
          </div>
          <div className="bg-white rounded-xl shadow-md p-6 text-center border border-gray-200">
            <div className="text-3xl font-bold text-blue-600 mb-2">100%</div>
            <div className="text-gray-600 text-sm">Open Source</div>
          </div>
          <div className="bg-white rounded-xl shadow-md p-6 text-center border border-gray-200">
            <div className="text-3xl font-bold text-purple-600 mb-2">∞</div>
            <div className="text-gray-600 text-sm">Customization</div>
          </div>
        </div>
      </div>
    </div>
  );
}
