/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetCurrentUser"];
        put: operations["UpdateCurrentUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/locale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["UpdateCurrentUserLocale"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all active sessions for the current user */
        get: operations["GetUserSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Revoke a specific session */
        post: operations["RevokeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/revoke-all-others": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Revoke all other sessions (keep current session active) */
        post: operations["RevokeAllOtherSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get current session information */
        get: operations["GetCurrentSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPayrollRecords"];
        put?: never;
        post: operations["CreatePayrollRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payroll/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProcessPayroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo/provision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProvisionDatabase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetDatabaseInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["DeleteDatabase"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo/databases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListAllDatabases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo/organizations/{organizationId}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetDatabaseInfoByOrganization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo/rpc/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo/rpc/search_read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SearchRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo/rpc/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo/rpc/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo/rpc/write": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Write"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo/rpc/unlink": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Unlink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo/rpc/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Execute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetInvoices"];
        put?: never;
        post: operations["CreateInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hisabiq/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all invoices for the authenticated user's organization */
        get: operations["GetInvoices"];
        put?: never;
        /** @description Create a new invoice */
        post: operations["CreateInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hisabiq/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get chart of accounts */
        get: operations["GetAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetEmployees"];
        put?: never;
        post: operations["CreateEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetDeals"];
        put?: never;
        post: operations["CreateDeal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetContacts"];
        put?: never;
        post: operations["CreateContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get available connector types and their field definitions */
        get: operations["GetConnectorTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/types/{type}/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get field definitions for a specific connector type */
        get: operations["GetFieldDefinitions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all connectors for the current organization */
        get: operations["ListConnectors"];
        put?: never;
        /** @description Create a new connector */
        post: operations["CreateConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{connectorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a specific connector by ID */
        get: operations["GetConnector"];
        /** @description Update a connector */
        put: operations["UpdateConnector"];
        post?: never;
        /** @description Delete a connector */
        delete: operations["DeleteConnector"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{connectorId}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Test connection for a connector */
        post: operations["TestConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{connectorId}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get health status for a connector */
        get: operations["GetHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{connectorId}/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Execute a raw SQL query on an external database */
        post: operations["ExecuteQuery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{connectorId}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get schema information (tables and views) from external database */
        get: operations["GetSchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{connectorId}/schema/{schemaName}/tables/{tableName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get table preview (structure and sample data) */
        get: operations["GetTablePreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{connectorId}/schema/{schemaName}/tables/{tableName}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Search a table across multiple columns */
        get: operations["SearchTable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/mappings/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Get suggested field mappings for a target entity */
        post: operations["SuggestMappings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Change password for authenticated user */
        post: operations["ChangePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/request-password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Request password reset (will send email in future)
         *     For now, this endpoint logs the request for future email implementation
         */
        post: operations["RequestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetAccounts"];
        put?: never;
        post: operations["CreateAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Locale: "en" | "ar";
        UserProfileResponse: {
            id: string;
            email: string;
            firstName?: string | null;
            lastName?: string | null;
            preferredLocale: components["schemas"]["Locale"];
            organizationId: string;
            organization?: {
                slug: string;
                name: string;
                id: string;
            };
        };
        UpdateProfileRequest: {
            firstName?: string;
            lastName?: string;
            preferredLocale?: components["schemas"]["Locale"];
        };
        UpdateLocaleRequest: {
            locale: components["schemas"]["Locale"];
        };
        SessionInfo: {
            id: string;
            userId: string;
            deviceName?: string | null;
            ipAddress: string;
            location?: string | null;
            loginMethod: string;
            /** Format: date-time */
            lastActivity: string;
            /** Format: date-time */
            createdAt: string;
            isActive: boolean;
        };
        SessionListResponse: {
            sessions: components["schemas"]["SessionInfo"][];
            currentSessionId?: string;
        };
        RevokeSessionResponse: {
            message: string;
            revokedSessionId: string;
        };
        PayrollRecord: {
            id: string;
            employeeId: string;
            period: string;
            /** Format: double */
            basicSalary: number;
            /** Format: double */
            allowances: number;
            /** Format: double */
            deductions: number;
            /** Format: double */
            netPay: number;
            /** @enum {string} */
            status: "DRAFT" | "PROCESSED" | "PAID";
        };
        PayrollCreateRequest: {
            employeeId: string;
            period: string;
            /** Format: double */
            basicSalary: number;
            /** Format: double */
            allowances: number;
            /** Format: double */
            deductions: number;
        };
        OdooProvisionResponse: {
            success: boolean;
            databaseName: string;
            adminLogin: string;
            adminPassword: string;
            odooUrl: string;
            loginUrl: string;
        };
        OdooInfoResponse: {
            databaseName: string;
            exists: boolean;
            loginUrl: string | null;
        };
        OdooDeleteResponse: {
            success: boolean;
            message: string;
        };
        OdooListResponse: {
            databases: string[];
        };
        OdooSearchRequest: {
            model: string;
            domain?: unknown[];
            /** Format: double */
            limit?: number;
            /** Format: double */
            offset?: number;
            order?: string;
        };
        /** @description Construct a type with a set of properties K of type T */
        "Record_string.unknown_": {
            [key: string]: unknown;
        };
        OdooSearchReadRequest: {
            model: string;
            domain?: unknown[];
            fields?: string[];
            /** Format: double */
            limit?: number;
            /** Format: double */
            offset?: number;
            order?: string;
            context?: components["schemas"]["Record_string.unknown_"];
        };
        OdooReadRequest: {
            model: string;
            ids: number[];
            fields?: string[];
            context?: components["schemas"]["Record_string.unknown_"];
        };
        OdooCreateRequest: {
            model: string;
            values: components["schemas"]["Record_string.unknown_"];
            context?: components["schemas"]["Record_string.unknown_"];
        };
        OdooWriteRequest: {
            model: string;
            ids: number[];
            values: components["schemas"]["Record_string.unknown_"];
            context?: components["schemas"]["Record_string.unknown_"];
        };
        OdooUnlinkRequest: {
            model: string;
            ids: number[];
            context?: components["schemas"]["Record_string.unknown_"];
        };
        OdooExecuteRequest: {
            model: string;
            method: string;
            args?: unknown[];
            kwargs?: components["schemas"]["Record_string.unknown_"];
        };
        Invoice: {
            id: string;
            number: string;
            /** @enum {string} */
            type: "SALES" | "PURCHASE";
            date: string;
            /** Format: double */
            total: number;
            status: string;
        };
        InvoiceCreateRequest: {
            /** @enum {string} */
            type: "SALES" | "PURCHASE";
            customerId?: string;
            supplierId?: string;
            date: string;
            dueDate?: string;
            items: {
                /** Format: double */
                unitPrice: number;
                /** Format: double */
                quantity: number;
                description: string;
            }[];
        };
        HealthCheck: {
            /** @enum {string} */
            status: "ok" | "error";
            timestamp: string;
            /** Format: double */
            uptime: number;
            version: string;
        };
        Employee: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            position: string;
            /** Format: double */
            salary: number;
            startDate: string;
        };
        EmployeeCreateRequest: {
            firstName: string;
            lastName: string;
            email: string;
            position: string;
            /** Format: double */
            salary: number;
            startDate: string;
        };
        Deal: {
            id: string;
            title: string;
            /** Format: double */
            value: number;
            /** @enum {string} */
            stage: "PROSPECT" | "QUALIFIED" | "PROPOSAL" | "NEGOTIATION" | "CLOSED_WON" | "CLOSED_LOST";
            contactId: string;
            expectedCloseDate: string;
            /** Format: double */
            probability: number;
        };
        DealCreateRequest: {
            title: string;
            /** Format: double */
            value: number;
            contactId: string;
            expectedCloseDate: string;
            /** Format: double */
            probability: number;
        };
        Contact: {
            id: string;
            name: string;
            email: string;
            phone: string;
            company?: string;
            /** @enum {string} */
            type: "LEAD" | "CUSTOMER" | "VENDOR";
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
        };
        ContactCreateRequest: {
            name: string;
            email: string;
            phone: string;
            company?: string;
            /** @enum {string} */
            type: "LEAD" | "CUSTOMER" | "VENDOR";
        };
        /** @enum {string} */
        ConnectorType: "postgresql" | "mysql" | "mssql";
        ConnectorResponse: {
            id: string;
            organizationId: string;
            name: string;
            description?: string;
            type: components["schemas"]["ConnectorType"];
            isActive: boolean;
            tags: string[];
            metadata: components["schemas"]["Record_string.unknown_"];
            lastConnectionTest?: string;
            lastConnectionStatus?: string;
            lastConnectionError?: string;
            createdAt: string;
            updatedAt: string;
        };
        PostgreSQLConfig: {
            host: string;
            /** Format: double */
            port: number;
            database: string;
            username: string;
            password: string;
            ssl?: boolean;
            url?: string;
            apiKey?: string;
            authToken?: string;
            /** Format: double */
            maxConnections?: number;
            /** Format: double */
            connectionTimeout?: number;
        };
        MySQLConfig: {
            host: string;
            /** Format: double */
            port: number;
            database: string;
            username: string;
            password: string;
            ssl?: boolean;
            url?: string;
            apiKey?: string;
            authToken?: string;
            /** Format: double */
            maxConnections?: number;
            /** Format: double */
            connectionTimeout?: number;
        };
        MSSQLConnectorConfig: {
            host: string;
            /** Format: double */
            port: number;
            database: string;
            username: string;
            password: string;
            ssl?: boolean;
            url?: string;
            apiKey?: string;
            authToken?: string;
            encrypt?: boolean;
            trustServerCertificate?: boolean;
            /** Format: double */
            maxConnections?: number;
            /** Format: double */
            connectionTimeout?: number;
            /** Format: double */
            requestTimeout?: number;
        };
        CreateConnectorRequest: {
            name: string;
            description?: string;
            type: components["schemas"]["ConnectorType"];
            config: components["schemas"]["PostgreSQLConfig"] | components["schemas"]["MySQLConfig"] | components["schemas"]["MSSQLConnectorConfig"];
            tags?: string[];
            metadata?: components["schemas"]["Record_string.unknown_"];
        };
        UpdateConnectorRequest: {
            name?: string;
            description?: string;
            config?: components["schemas"]["PostgreSQLConfig"] | components["schemas"]["MySQLConfig"] | components["schemas"]["MSSQLConnectorConfig"];
            tags?: string[];
            metadata?: components["schemas"]["Record_string.unknown_"];
            isActive?: boolean;
        };
        QueryResponse: {
            rows: unknown[];
            /** Format: double */
            rowCount: number;
            /** Format: double */
            executionTime: number;
        };
        QueryRequest: {
            sql: string;
            params?: unknown[];
        };
        SchemaResponse: {
            tables: {
                /** @enum {string} */
                type: "table" | "view";
                name: string;
                schema: string;
            }[];
        };
        TablePreviewResponse: {
            schema: string;
            table: string;
            columns: {
                nullable: boolean;
                type: string;
                name: string;
            }[];
            sampleData: unknown[];
            /** Format: double */
            totalRows: number;
        };
        FieldMapping: {
            sourceColumn: string;
            targetField: string;
            /** @enum {string} */
            transform?: "lowercase" | "uppercase" | "trim" | "date" | "number" | "boolean";
            defaultValue?: unknown;
        };
        SuggestMappingsRequest: {
            sourceColumns: string[];
            /** @enum {string} */
            targetEntity: "contact" | "deal" | "company" | "invoice" | "employee" | "custom";
        };
        LoginResponse: {
            accessToken: string;
            refreshToken: string;
            /** Format: double */
            expiresIn: number;
            sessionId: string;
            user: {
                organization?: {
                    slug: string;
                    name: string;
                    id: string;
                };
                permissions: string[];
                roles: string[];
                lastName?: string | null;
                firstName?: string | null;
                email: string;
                id: string;
            };
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        RegisterRequest: {
            email: string;
            password: string;
            firstName?: string;
            lastName?: string;
            organizationName: string;
        };
        PasswordResetResponse: {
            message: string;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        RequestPasswordResetRequest: {
            email: string;
        };
        Account: {
            id: string;
            code: string;
            name: string;
            /** @enum {string} */
            type: "ASSET" | "LIABILITY" | "EQUITY" | "REVENUE" | "EXPENSE";
            /** Format: double */
            balance: number;
            parentId?: string;
        };
        AccountCreateRequest: {
            code: string;
            name: string;
            /** @enum {string} */
            type: "ASSET" | "LIABILITY" | "EQUITY" | "REVENUE" | "EXPENSE";
            parentId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    UpdateCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description User profile updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    UpdateCurrentUserLocale: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLocaleRequest"];
            };
        };
        responses: {
            /** @description User locale updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        locale: components["schemas"]["Locale"];
                        message: string;
                    };
                };
            };
        };
    };
    GetUserSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
        };
    };
    RevokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeSessionResponse"];
                };
            };
        };
    };
    RevokeAllOtherSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All other sessions revoked successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: double */
                        revokedCount: number;
                        message: string;
                    };
                };
            };
        };
    };
    GetCurrentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        userInfo: {
                            permissions: string[];
                            roles: string[];
                            email: string;
                            userId: string;
                        };
                        sessionInfo?: unknown;
                        sessionId?: string;
                    };
                };
            };
        };
    };
    GetPayrollRecords: {
        parameters: {
            query?: {
                _page?: number;
                _limit?: number;
                _period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: double */
                        limit: number;
                        /** Format: double */
                        page: number;
                        /** Format: double */
                        total: number;
                        records: components["schemas"]["PayrollRecord"][];
                    };
                };
            };
        };
    };
    CreatePayrollRecord: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayrollCreateRequest"];
            };
        };
        responses: {
            /** @description Payroll record created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayrollRecord"];
                };
            };
        };
    };
    ProcessPayroll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    period: string;
                };
            };
        };
        responses: {
            /** @description Payroll processed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    ProvisionDatabase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OdooProvisionResponse"];
                };
            };
        };
    };
    GetDatabaseInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OdooInfoResponse"];
                };
            };
        };
    };
    DeleteDatabase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OdooDeleteResponse"];
                };
            };
        };
    };
    ListAllDatabases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OdooListResponse"];
                };
            };
        };
    };
    GetDatabaseInfoByOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OdooInfoResponse"];
                };
            };
        };
    };
    Search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OdooSearchRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number[];
                };
            };
        };
    };
    SearchRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OdooSearchReadRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record_string.unknown_"][];
                };
            };
        };
    };
    Read: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OdooReadRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record_string.unknown_"][];
                };
            };
        };
    };
    Create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OdooCreateRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: double */
                        id: number;
                    };
                };
            };
        };
    };
    Write: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OdooWriteRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
        };
    };
    Unlink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OdooUnlinkRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
        };
    };
    Execute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OdooExecuteRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    GetInvoices: {
        parameters: {
            query?: {
                _page?: number;
                _limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: double */
                        limit: number;
                        /** Format: double */
                        page: number;
                        /** Format: double */
                        total: number;
                        invoices: components["schemas"]["Invoice"][];
                    };
                };
            };
        };
    };
    CreateInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceCreateRequest"];
            };
        };
        responses: {
            /** @description Invoice created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
        };
    };
    GetInvoices: {
        parameters: {
            query?: {
                _page?: number;
                _limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: double */
                        limit: number;
                        /** Format: double */
                        page: number;
                        /** Format: double */
                        total: number;
                        invoices: components["schemas"]["Invoice"][];
                    };
                };
            };
        };
    };
    CreateInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceCreateRequest"];
            };
        };
        responses: {
            /** @description Invoice created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
        };
    };
    GetAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        parentId?: string;
                        type: string;
                        name: string;
                        code: string;
                        id: string;
                    }[];
                };
            };
        };
    };
    GetHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheck"];
                };
            };
        };
    };
    GetEmployees: {
        parameters: {
            query?: {
                _page?: number;
                _limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: double */
                        limit: number;
                        /** Format: double */
                        page: number;
                        /** Format: double */
                        total: number;
                        employees: components["schemas"]["Employee"][];
                    };
                };
            };
        };
    };
    CreateEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeCreateRequest"];
            };
        };
        responses: {
            /** @description Employee created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
        };
    };
    GetDeals: {
        parameters: {
            query?: {
                _page?: number;
                _limit?: number;
                _stage?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: double */
                        limit: number;
                        /** Format: double */
                        page: number;
                        /** Format: double */
                        total: number;
                        deals: components["schemas"]["Deal"][];
                    };
                };
            };
        };
    };
    CreateDeal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DealCreateRequest"];
            };
        };
        responses: {
            /** @description Deal created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deal"];
                };
            };
        };
    };
    GetContacts: {
        parameters: {
            query?: {
                _page?: number;
                _limit?: number;
                _type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: double */
                        limit: number;
                        /** Format: double */
                        page: number;
                        /** Format: double */
                        total: number;
                        contacts: components["schemas"]["Contact"][];
                    };
                };
            };
        };
    };
    CreateContact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactCreateRequest"];
            };
        };
        responses: {
            /** @description Contact created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contact"];
                };
            };
        };
    };
    GetConnectorTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        optionalFields: string[];
                        requiredFields: string[];
                        description: string;
                        name: string;
                        type: components["schemas"]["ConnectorType"];
                    }[];
                };
            };
        };
    };
    GetFieldDefinitions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: components["schemas"]["ConnectorType"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        helpText?: string;
                        defaultValue?: unknown;
                        required: boolean;
                        placeholder?: string;
                        label: string;
                        /** @enum {string} */
                        type: "text" | "number" | "password" | "boolean";
                        name: string;
                    }[];
                };
            };
        };
    };
    ListConnectors: {
        parameters: {
            query?: {
                type?: components["schemas"]["ConnectorType"];
                isActive?: boolean;
                tags?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorResponse"][];
                };
            };
        };
    };
    CreateConnector: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConnectorRequest"];
            };
        };
        responses: {
            /** @description Connector created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorResponse"];
                };
            };
        };
    };
    GetConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorResponse"];
                };
            };
        };
    };
    UpdateConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConnectorRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
        };
    };
    DeleteConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
        };
    };
    TestConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                        metadata?: components["schemas"]["Record_string.unknown_"];
                        /** Format: double */
                        latency?: number;
                        message: string;
                        status: string;
                    };
                };
            };
        };
    };
    GetHealth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        details?: components["schemas"]["Record_string.unknown_"];
                        message?: string;
                        healthy: boolean;
                    };
                };
            };
        };
    };
    ExecuteQuery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
        };
    };
    GetSchema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaResponse"];
                };
            };
        };
    };
    GetTablePreview: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                connectorId: string;
                schemaName: string;
                tableName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TablePreviewResponse"];
                };
            };
        };
    };
    SearchTable: {
        parameters: {
            query: {
                searchTerm: string;
                searchColumns: string;
                limit?: number;
            };
            header?: never;
            path: {
                connectorId: string;
                schemaName: string;
                tableName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
        };
    };
    SuggestMappings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestMappingsRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldMapping"][];
                };
            };
        };
    };
    Login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    Register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    Logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    ChangePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetResponse"];
                };
            };
        };
    };
    RequestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestPasswordResetRequest"];
            };
        };
        responses: {
            /** @description Password reset email sent (if account exists) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetResponse"];
                };
            };
        };
    };
    GetAccounts: {
        parameters: {
            query?: {
                _type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"][];
                };
            };
        };
    };
    CreateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreateRequest"];
            };
        };
        responses: {
            /** @description Account created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
        };
    };
}
