/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetCurrentUser"];
        put: operations["UpdateCurrentUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/locale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["UpdateCurrentUserLocale"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Upload a file to storage */
        post: operations["UploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/upload/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Upload multiple files */
        post: operations["UploadFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/files/{fileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get file metadata */
        get: operations["GetFile"];
        put?: never;
        post?: never;
        /** @description Delete file */
        delete: operations["DeleteFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/files/{fileId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Download file */
        get: operations["DownloadFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/files/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Search files */
        get: operations["SearchFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create folder */
        post: operations["CreateFolder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/folders/{folderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get folder contents */
        get: operations["GetFolderContents"];
        put?: never;
        post?: never;
        /** @description Delete folder */
        delete: operations["DeleteFolder"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get storage quota information */
        get: operations["GetQuota"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPayrollRecords"];
        put?: never;
        post: operations["CreatePayrollRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payroll/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProcessPayroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo/provision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProvisionDatabase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetDatabaseInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["DeleteDatabase"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DuplicateDatabase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["BackupDatabase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo/databases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListAllDatabases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo/organizations/{organizationId}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetDatabaseInfoByOrganization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo/rpc/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo/rpc/search_read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SearchRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo/rpc/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo/rpc/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo/rpc/write": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Write"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo/rpc/unlink": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Unlink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odoo/rpc/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Execute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nas/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Connect to a NAS drive
         *     Supports SMB/CIFS, NFS, and WebDAV protocols
         */
        post: operations["ConnectNAS"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nas/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Disconnect from a NAS drive */
        delete: operations["DisconnectNAS"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nas/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get status of all connected NAS drives */
        get: operations["GetAllNASStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nas/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Disconnect from all NAS drives */
        delete: operations["DisconnectAll"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetInvoices"];
        put?: never;
        post: operations["CreateInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hisabiq/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all invoices for the authenticated user's organization */
        get: operations["GetHisabiqInvoices"];
        put?: never;
        /** @description Create a new invoice */
        post: operations["CreateHisabiqInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hisabiq/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get chart of accounts */
        get: operations["GetHisabiqAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetEmployees"];
        put?: never;
        post: operations["CreateEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetDeals"];
        put?: never;
        post: operations["CreateDeal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetContacts"];
        put?: never;
        post: operations["CreateContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetConnectorTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/types/{type}/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetFieldDefinitions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListConnectors"];
        put?: never;
        post: operations["CreateConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{connectorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetConnector"];
        put: operations["UpdateConnector"];
        post?: never;
        delete: operations["DeleteConnector"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{connectorId}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TestConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{connectorId}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetConnectorHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{connectorId}/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ExecuteQuery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{connectorId}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetSchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{connectorId}/schema/{schemaName}/tables/{tableName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetTablePreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{connectorId}/schema/{schemaName}/tables/{tableName}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SearchTable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/mappings/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SuggestMappings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetAccounts"];
        put?: never;
        post: operations["CreateAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Locale: "en" | "ar";
        UserProfileResponse: {
            id: string;
            email: string;
            name?: string | null;
            preferredLocale: components["schemas"]["Locale"];
            organizationId: string | null;
            organization?: {
                slug: string;
                name: string;
                id: string;
            };
        };
        UpdateProfileRequest: {
            name?: string;
            preferredLocale?: components["schemas"]["Locale"];
        };
        UpdateLocaleRequest: {
            locale: components["schemas"]["Locale"];
        };
        /** @description Construct a type with a set of properties K of type T */
        "Record_string.unknown_": {
            [key: string]: unknown;
        };
        FileMetadata: {
            id: string;
            name: string;
            path: string;
            /** Format: double */
            size: number;
            mimeType: string;
            createdAt: string;
            modifiedAt: string;
            createdBy: string;
            modifiedBy?: string;
            folderId?: string;
            tags?: string[];
            metadata?: components["schemas"]["Record_string.unknown_"];
        };
        FolderMetadata: {
            id: string;
            name: string;
            path: string;
            parentId?: string;
            createdAt: string;
            modifiedAt: string;
            createdBy: string;
            modifiedBy?: string;
            /** Format: double */
            fileCount: number;
            /** Format: double */
            subFolderCount: number;
        };
        CreateFolderRequest: {
            name: string;
            parentId?: string;
        };
        PayrollRecord: {
            id: string;
            employeeId: string;
            period: string;
            /** Format: double */
            basicSalary: number;
            /** Format: double */
            allowances: number;
            /** Format: double */
            deductions: number;
            /** Format: double */
            netPay: number;
            /** @enum {string} */
            status: "DRAFT" | "PROCESSED" | "PAID";
        };
        PayrollCreateRequest: {
            employeeId: string;
            period: string;
            /** Format: double */
            basicSalary: number;
            /** Format: double */
            allowances: number;
            /** Format: double */
            deductions: number;
        };
        OdooProvisionResponse: {
            success: boolean;
            databaseName: string;
            adminLogin: string;
            adminPassword: string;
            odooUrl: string;
            loginUrl: string;
        };
        OdooInfoResponse: {
            databaseName: string;
            exists: boolean;
            loginUrl: string | null;
        };
        OdooDeleteResponse: {
            success: boolean;
            message: string;
        };
        OdooDuplicateResponse: {
            success: boolean;
            originalName: string;
            newName: string;
        };
        OdooDuplicateRequest: {
            newName: string;
            neutralize?: boolean;
        };
        OdooListResponse: {
            databases: string[];
        };
        OdooSearchRequest: {
            model: string;
            domain?: unknown[];
            /** Format: double */
            limit?: number;
            /** Format: double */
            offset?: number;
            order?: string;
        };
        OdooSearchReadRequest: {
            model: string;
            domain?: unknown[];
            fields?: string[];
            /** Format: double */
            limit?: number;
            /** Format: double */
            offset?: number;
            order?: string;
            context?: components["schemas"]["Record_string.unknown_"];
        };
        OdooReadRequest: {
            model: string;
            ids: number[];
            fields?: string[];
            context?: components["schemas"]["Record_string.unknown_"];
        };
        OdooCreateRequest: {
            model: string;
            values: components["schemas"]["Record_string.unknown_"];
            context?: components["schemas"]["Record_string.unknown_"];
        };
        OdooWriteRequest: {
            model: string;
            ids: number[];
            values: components["schemas"]["Record_string.unknown_"];
            context?: components["schemas"]["Record_string.unknown_"];
        };
        OdooUnlinkRequest: {
            model: string;
            ids: number[];
            context?: components["schemas"]["Record_string.unknown_"];
        };
        OdooExecuteRequest: {
            model: string;
            method: string;
            args?: unknown[];
            kwargs?: components["schemas"]["Record_string.unknown_"];
        };
        NASConnectionStatus: {
            connected: boolean;
            mountPoint?: string;
            error?: string;
            /** Format: double */
            freeSpace?: number;
            /** Format: double */
            totalSpace?: number;
            /** Format: double */
            usedSpace?: number;
        };
        ConnectNASRequest: {
            name: string;
            /** @enum {string} */
            type: "smb" | "nfs" | "webdav";
            host: string;
            shareName: string;
            username?: string;
            password?: string;
            domain?: string;
            mountPoint?: string;
            /** Format: double */
            port?: number;
        };
        NASStatusResponse: {
            [key: string]: components["schemas"]["NASConnectionStatus"];
        };
        Invoice: {
            id: string;
            number: string;
            /** @enum {string} */
            type: "SALES" | "PURCHASE";
            date: string;
            /** Format: double */
            total: number;
            status: string;
        };
        InvoiceCreateRequest: {
            /** @enum {string} */
            type: "SALES" | "PURCHASE";
            customerId?: string;
            supplierId?: string;
            date: string;
            dueDate?: string;
            items: {
                /** Format: double */
                unitPrice: number;
                /** Format: double */
                quantity: number;
                description: string;
            }[];
        };
        HealthCheck: {
            /** @enum {string} */
            status: "ok" | "error";
            timestamp: string;
            /** Format: double */
            uptime: number;
            version: string;
        };
        Employee: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            position: string;
            /** Format: double */
            salary: number;
            startDate: string;
        };
        EmployeeCreateRequest: {
            firstName: string;
            lastName: string;
            email: string;
            position: string;
            /** Format: double */
            salary: number;
            startDate: string;
        };
        Deal: {
            id: string;
            title: string;
            /** Format: double */
            value: number;
            /** @enum {string} */
            stage: "PROSPECT" | "QUALIFIED" | "PROPOSAL" | "NEGOTIATION" | "CLOSED_WON" | "CLOSED_LOST";
            contactId: string;
            expectedCloseDate: string;
            /** Format: double */
            probability: number;
        };
        DealCreateRequest: {
            title: string;
            /** Format: double */
            value: number;
            contactId: string;
            expectedCloseDate: string;
            /** Format: double */
            probability: number;
        };
        Contact: {
            id: string;
            name: string;
            email: string;
            phone: string;
            company?: string;
            /** @enum {string} */
            type: "LEAD" | "CUSTOMER" | "VENDOR";
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
        };
        ContactCreateRequest: {
            name: string;
            email: string;
            phone: string;
            company?: string;
            /** @enum {string} */
            type: "LEAD" | "CUSTOMER" | "VENDOR";
        };
        /** @enum {string} */
        ConnectorType: "postgresql" | "mysql" | "mssql" | "storage_local" | "storage_webdav" | "storage_smb" | "storage_cloud";
        ConnectorResponse: {
            id: string;
            organizationId: string;
            name: string;
            description?: string;
            type: components["schemas"]["ConnectorType"];
            isActive: boolean;
            tags: string[];
            metadata: components["schemas"]["Record_string.unknown_"];
            lastConnectionTest?: string;
            lastConnectionStatus?: string;
            lastConnectionError?: string;
            createdAt: string;
            updatedAt: string;
        };
        ConnectorConfig: {
            host?: string;
            /** Format: double */
            port?: number;
            database?: string;
            username?: string;
            password?: string;
            ssl?: boolean;
            url?: string;
            apiKey?: string;
            authToken?: string;
        } & {
            [key: string]: unknown;
        };
        CreateConnectorRequest: {
            name: string;
            description?: string;
            type: components["schemas"]["ConnectorType"];
            config: components["schemas"]["ConnectorConfig"];
            tags?: string[];
            metadata?: components["schemas"]["Record_string.unknown_"];
        };
        UpdateConnectorRequest: {
            name?: string;
            description?: string;
            config?: components["schemas"]["ConnectorConfig"];
            tags?: string[];
            metadata?: components["schemas"]["Record_string.unknown_"];
            isActive?: boolean;
        };
        QueryResponse: {
            rows: unknown[];
            /** Format: double */
            rowCount: number;
            /** Format: double */
            executionTime: number;
        };
        QueryRequest: {
            sql: string;
            params?: unknown[];
        };
        SchemaResponse: {
            tables: {
                /** @enum {string} */
                type: "table" | "view";
                name: string;
                schema: string;
            }[];
        };
        TablePreviewResponse: {
            schema: string;
            table: string;
            columns: {
                nullable: boolean;
                type: string;
                name: string;
            }[];
            sampleData: unknown[];
            /** Format: double */
            totalRows: number;
        };
        FieldMapping: {
            sourceColumn: string;
            targetField: string;
            /** @enum {string} */
            transform?: "lowercase" | "uppercase" | "trim" | "date" | "number" | "boolean";
            defaultValue?: unknown;
        };
        SuggestMappingsRequest: {
            sourceColumns: string[];
            /** @enum {string} */
            targetEntity: "contact" | "deal" | "company" | "invoice" | "employee" | "custom";
        };
        Account: {
            id: string;
            code: string;
            name: string;
            /** @enum {string} */
            type: "ASSET" | "LIABILITY" | "EQUITY" | "REVENUE" | "EXPENSE";
            /** Format: double */
            balance: number;
            parentId?: string;
        };
        AccountCreateRequest: {
            code: string;
            name: string;
            /** @enum {string} */
            type: "ASSET" | "LIABILITY" | "EQUITY" | "REVENUE" | "EXPENSE";
            parentId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    UpdateCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description User profile updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    UpdateCurrentUserLocale: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLocaleRequest"];
            };
        };
        responses: {
            /** @description User locale updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        locale: components["schemas"]["Locale"];
                        message: string;
                    };
                };
            };
        };
    };
    UploadFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    folderId?: string;
                    tags?: string;
                    metadata?: string;
                };
            };
        };
        responses: {
            /** @description File uploaded successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileMetadata"];
                };
            };
        };
    };
    UploadFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    files: string;
                    folderId?: string;
                    tags?: string;
                    metadata?: string;
                };
            };
        };
        responses: {
            /** @description Files uploaded successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileMetadata"][];
                };
            };
        };
    };
    GetFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileMetadata"];
                };
            };
        };
    };
    DeleteFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DownloadFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SearchFiles: {
        parameters: {
            query?: {
                query?: string;
                folderId?: string;
                mimeTypes?: string[];
                tags?: string[];
                dateFrom?: string;
                dateTo?: string;
                createdBy?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        hasMore: boolean;
                        /** Format: double */
                        total: number;
                        files: components["schemas"]["FileMetadata"][];
                    };
                };
            };
        };
    };
    CreateFolder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFolderRequest"];
            };
        };
        responses: {
            /** @description Folder created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderMetadata"];
                };
            };
        };
    };
    GetFolderContents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        subFolders: components["schemas"]["FolderMetadata"][];
                        files: components["schemas"]["FileMetadata"][];
                        folder: components["schemas"]["FolderMetadata"];
                    };
                };
            };
        };
    };
    DeleteFolder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Folder deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetQuota: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        unit: string;
                        /** Format: double */
                        remaining: number;
                        /** Format: double */
                        total: number;
                        /** Format: double */
                        used: number;
                    };
                };
            };
        };
    };
    GetPayrollRecords: {
        parameters: {
            query?: {
                _page?: number;
                _limit?: number;
                _period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: double */
                        limit: number;
                        /** Format: double */
                        page: number;
                        /** Format: double */
                        total: number;
                        records: components["schemas"]["PayrollRecord"][];
                    };
                };
            };
        };
    };
    CreatePayrollRecord: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayrollCreateRequest"];
            };
        };
        responses: {
            /** @description Payroll record created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayrollRecord"];
                };
            };
        };
    };
    ProcessPayroll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    period: string;
                };
            };
        };
        responses: {
            /** @description Payroll processed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    ProvisionDatabase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OdooProvisionResponse"];
                };
            };
        };
    };
    GetDatabaseInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OdooInfoResponse"];
                };
            };
        };
    };
    DeleteDatabase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OdooDeleteResponse"];
                };
            };
        };
    };
    DuplicateDatabase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OdooDuplicateRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OdooDuplicateResponse"];
                };
            };
        };
    };
    BackupDatabase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: string;
                        success: boolean;
                    };
                };
            };
        };
    };
    ListAllDatabases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OdooListResponse"];
                };
            };
        };
    };
    GetDatabaseInfoByOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OdooInfoResponse"];
                };
            };
        };
    };
    Search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OdooSearchRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number[];
                };
            };
        };
    };
    SearchRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OdooSearchReadRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record_string.unknown_"][];
                };
            };
        };
    };
    Read: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OdooReadRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record_string.unknown_"][];
                };
            };
        };
    };
    Create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OdooCreateRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: double */
                        id: number;
                    };
                };
            };
        };
    };
    Write: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OdooWriteRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
        };
    };
    Unlink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OdooUnlinkRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
        };
    };
    Execute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OdooExecuteRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ConnectNAS: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectNASRequest"];
            };
        };
        responses: {
            /** @description NAS connected successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NASConnectionStatus"];
                };
            };
        };
    };
    DisconnectNAS: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description NAS disconnected successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetAllNASStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NASStatusResponse"];
                };
            };
        };
    };
    DisconnectAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All NAS drives disconnected */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    GetInvoices: {
        parameters: {
            query?: {
                _page?: number;
                _limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: double */
                        limit: number;
                        /** Format: double */
                        page: number;
                        /** Format: double */
                        total: number;
                        invoices: components["schemas"]["Invoice"][];
                    };
                };
            };
        };
    };
    CreateInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceCreateRequest"];
            };
        };
        responses: {
            /** @description Invoice created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
        };
    };
    GetHisabiqInvoices: {
        parameters: {
            query?: {
                _page?: number;
                _limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: double */
                        limit: number;
                        /** Format: double */
                        page: number;
                        /** Format: double */
                        total: number;
                        invoices: components["schemas"]["Invoice"][];
                    };
                };
            };
        };
    };
    CreateHisabiqInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceCreateRequest"];
            };
        };
        responses: {
            /** @description Invoice created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
        };
    };
    GetHisabiqAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        parentId?: string;
                        type: string;
                        name: string;
                        code: string;
                        id: string;
                    }[];
                };
            };
        };
    };
    GetHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheck"];
                };
            };
        };
    };
    GetEmployees: {
        parameters: {
            query?: {
                _page?: number;
                _limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: double */
                        limit: number;
                        /** Format: double */
                        page: number;
                        /** Format: double */
                        total: number;
                        employees: components["schemas"]["Employee"][];
                    };
                };
            };
        };
    };
    CreateEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeCreateRequest"];
            };
        };
        responses: {
            /** @description Employee created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
        };
    };
    GetDeals: {
        parameters: {
            query?: {
                _page?: number;
                _limit?: number;
                _stage?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: double */
                        limit: number;
                        /** Format: double */
                        page: number;
                        /** Format: double */
                        total: number;
                        deals: components["schemas"]["Deal"][];
                    };
                };
            };
        };
    };
    CreateDeal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DealCreateRequest"];
            };
        };
        responses: {
            /** @description Deal created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deal"];
                };
            };
        };
    };
    GetContacts: {
        parameters: {
            query?: {
                _page?: number;
                _limit?: number;
                _type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: double */
                        limit: number;
                        /** Format: double */
                        page: number;
                        /** Format: double */
                        total: number;
                        contacts: components["schemas"]["Contact"][];
                    };
                };
            };
        };
    };
    CreateContact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactCreateRequest"];
            };
        };
        responses: {
            /** @description Contact created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contact"];
                };
            };
        };
    };
    GetConnectorTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        optionalFields: string[];
                        requiredFields: string[];
                        description: string;
                        name: string;
                        type: components["schemas"]["ConnectorType"];
                    }[];
                };
            };
        };
    };
    GetFieldDefinitions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: components["schemas"]["ConnectorType"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        helpText?: string;
                        defaultValue?: unknown;
                        required: boolean;
                        placeholder?: string;
                        label: string;
                        /** @enum {string} */
                        type: "text" | "number" | "password" | "boolean";
                        name: string;
                    }[];
                };
            };
        };
    };
    ListConnectors: {
        parameters: {
            query?: {
                type?: components["schemas"]["ConnectorType"];
                isActive?: boolean;
                tags?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorResponse"][];
                };
            };
        };
    };
    CreateConnector: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConnectorRequest"];
            };
        };
        responses: {
            /** @description Connector created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorResponse"];
                };
            };
        };
    };
    GetConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorResponse"];
                };
            };
        };
    };
    UpdateConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConnectorRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
        };
    };
    DeleteConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
        };
    };
    TestConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                        metadata?: components["schemas"]["Record_string.unknown_"];
                        /** Format: double */
                        latency?: number;
                        message: string;
                        status: string;
                    };
                };
            };
        };
    };
    GetConnectorHealth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        details?: components["schemas"]["Record_string.unknown_"];
                        message?: string;
                        healthy: boolean;
                    };
                };
            };
        };
    };
    ExecuteQuery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
        };
    };
    GetSchema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaResponse"];
                };
            };
        };
    };
    GetTablePreview: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                connectorId: string;
                schemaName: string;
                tableName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TablePreviewResponse"];
                };
            };
        };
    };
    SearchTable: {
        parameters: {
            query: {
                searchTerm: string;
                searchColumns: string;
                limit?: number;
            };
            header?: never;
            path: {
                connectorId: string;
                schemaName: string;
                tableName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
        };
    };
    SuggestMappings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestMappingsRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldMapping"][];
                };
            };
        };
    };
    GetAccounts: {
        parameters: {
            query?: {
                _type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"][];
                };
            };
        };
    };
    CreateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreateRequest"];
            };
        };
        responses: {
            /** @description Account created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
        };
    };
}
