CREATE TYPE "hr"."allocation_unit" AS ENUM('day', 'hour');
CREATE TYPE "hr"."payslip_line_category" AS ENUM('ALW', 'DED', 'BASIC', 'GROSS', 'NET');
CREATE TYPE "hr"."request_unit" AS ENUM('day', 'hour');
CREATE TYPE "finance"."tax_amount_type" AS ENUM('percent', 'division', 'fixed');
CREATE TYPE "finance"."tax_scope" AS ENUM('sale', 'purchase', 'none');
CREATE TYPE "finance"."tax_type" AS ENUM('sale', 'purchase', 'none');
CREATE TYPE "hr"."time_type" AS ENUM('leave', 'other');
CREATE TYPE "hr"."validation_type" AS ENUM('no_validation', 'hr', 'manager', 'both');
CREATE TYPE "hr"."wage_type" AS ENUM('monthly', 'hourly');
ALTER TABLE "finance"."taxes" ALTER COLUMN "amount_type" SET DEFAULT 'percent'::"finance"."tax_amount_type";
ALTER TABLE "finance"."taxes" ALTER COLUMN "amount_type" SET DATA TYPE "finance"."tax_amount_type" USING "amount_type"::"finance"."tax_amount_type";
ALTER TABLE "finance"."taxes" ALTER COLUMN "tax_scope" SET DATA TYPE "finance"."tax_scope" USING "tax_scope"::"finance"."tax_scope";
ALTER TABLE "finance"."taxes" ALTER COLUMN "type_of_tax" SET DATA TYPE "finance"."tax_type" USING "type_of_tax"::"finance"."tax_type";
ALTER TABLE "hr"."payslip_lines" ALTER COLUMN "category" SET DATA TYPE "hr"."payslip_line_category" USING "category"::"hr"."payslip_line_category";
ALTER TABLE "hr"."leave_types" ALTER COLUMN "allocation_unit" SET DEFAULT 'day'::"hr"."allocation_unit";
ALTER TABLE "hr"."leave_types" ALTER COLUMN "allocation_unit" SET DATA TYPE "hr"."allocation_unit" USING "allocation_unit"::"hr"."allocation_unit";
ALTER TABLE "hr"."leave_types" ALTER COLUMN "allocation_unit" SET NOT NULL;
ALTER TABLE "hr"."leave_types" ALTER COLUMN "request_unit" SET DEFAULT 'day'::"hr"."request_unit";
ALTER TABLE "hr"."leave_types" ALTER COLUMN "request_unit" SET DATA TYPE "hr"."request_unit" USING "request_unit"::"hr"."request_unit";
ALTER TABLE "hr"."leave_types" ALTER COLUMN "request_unit" SET NOT NULL;
ALTER TABLE "hr"."leave_types" ALTER COLUMN "time_type" SET DEFAULT 'leave'::"hr".time_type;
ALTER TABLE "hr"."leave_types" ALTER COLUMN "time_type" SET DATA TYPE "hr"."time_type" USING "time_type"::"hr"."time_type";
ALTER TABLE "hr"."leave_types" ALTER COLUMN "time_type" SET NOT NULL;
ALTER TABLE "hr"."leave_types" ALTER COLUMN "validation_type" SET DEFAULT 'no_validation'::"hr"."validation_type";
ALTER TABLE "hr"."leave_types" ALTER COLUMN "validation_type" SET DATA TYPE "hr"."validation_type" USING "validation_type"::"hr"."validation_type";
ALTER TABLE "hr"."leave_types" ALTER COLUMN "validation_type" SET NOT NULL;
ALTER TABLE "hr"."contracts" ALTER COLUMN "wage_type" SET DEFAULT 'monthly'::"hr"."wage_type";
ALTER TABLE "hr"."contracts" ALTER COLUMN "wage_type" SET DATA TYPE "hr"."wage_type" USING "wage_type"::"hr"."wage_type";
ALTER TABLE "hr"."contracts" ALTER COLUMN "wage_type" SET NOT NULL;
