CREATE TYPE "finance"."account_internal_type" AS ENUM('receivable', 'payable', 'liquidity', 'other');
CREATE TYPE "finance"."account_type" AS ENUM('asset', 'liability', 'equity', 'income', 'expense');
CREATE TYPE "audit"."audit_category" AS ENUM('certification', 'financial', 'operational', 'compliance');
CREATE TYPE "audit"."audit_type" AS ENUM('ICV', 'ISO_9001', 'ISO_14001', 'ISO_45001', 'financial_audit', 'internal_audit', 'compliance_audit', 'operational_audit');
CREATE TYPE "audit"."case_action" AS ENUM('created', 'updated', 'deleted', 'completed', 'archived', 'assigned', 'unassigned');
CREATE TYPE "audit"."case_entity_type" AS ENUM('case', 'scope', 'section', 'procedure', 'document', 'note');
CREATE TYPE "identity"."color_scheme" AS ENUM('blue', 'purple', 'green', 'orange', 'red', 'teal');
CREATE TYPE "identity"."density" AS ENUM('compact', 'comfortable', 'spacious');
CREATE TYPE "identity"."font_size" AS ENUM('small', 'medium', 'large');
CREATE TYPE "identity"."invitation_status" AS ENUM('pending', 'accepted', 'rejected', 'expired');
CREATE TYPE "system"."notification_type" AS ENUM('deadline', 'review', 'completed', 'team', 'assignment', 'comment', 'mention', 'reminder', 'alert', 'warning', 'error', 'info', 'success', 'approval_requested', 'approval_approved', 'approval_rejected', 'approval_cancelled', 'approval_reminder', 'request_submitted', 'request_updated', 'request_withdrawn', 'request_escalated', 'case_update', 'case_created', 'case_assigned', 'case_completed', 'case_overdue', 'case_archived', 'document', 'document_uploaded', 'document_reviewed', 'document_approved', 'document_rejected', 'invoice_created', 'invoice_submitted', 'invoice_approved', 'invoice_rejected', 'invoice_paid', 'invoice_overdue', 'invoice_cancelled', 'payment_received', 'payment_sent', 'payment_failed', 'payment_pending', 'bill_created', 'bill_submitted', 'bill_approved', 'bill_rejected', 'bill_paid', 'bill_overdue', 'expense_submitted', 'expense_approved', 'expense_rejected', 'expense_reimbursed', 'leave_requested', 'leave_approved', 'leave_rejected', 'leave_cancelled', 'leave_reminder', 'payslip_generated', 'payslip_available', 'contract_created', 'contract_expiring', 'contract_expired', 'contract_renewed', 'employee_onboarded', 'employee_offboarded', 'timesheet_submitted', 'timesheet_approved', 'timesheet_rejected', 'deal_created', 'deal_updated', 'deal_won', 'deal_lost', 'deal_assigned', 'contact_added', 'contact_updated', 'task_assigned', 'task_completed', 'task_overdue', 'task_reminder', 'meeting_scheduled', 'meeting_reminder', 'meeting_cancelled', 'follow_up_due');
CREATE TYPE "system"."related_entity_type" AS ENUM('case', 'document', 'audit_template', 'audit_scope', 'audit_section', 'audit_procedure', 'approval', 'approval_request', 'invoice', 'bill', 'payment', 'account', 'journal', 'employee', 'payslip', 'leave_request', 'leave_allocation', 'contract', 'department', 'contact', 'deal', 'task', 'organization', 'user', 'team');
CREATE TYPE "identity"."theme" AS ENUM('light', 'dark', 'auto');
ALTER TABLE "sales"."contacts" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "sales"."deals" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "finance"."invoice_items" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "finance"."invoices" DISABLE ROW LEVEL SECURITY;
DROP TABLE "sales"."contacts" CASCADE;
DROP TABLE "sales"."deals" CASCADE;
DROP TABLE "finance"."invoice_items" CASCADE;
DROP TABLE "finance"."invoices" CASCADE;
ALTER TABLE "identity"."invitations" ALTER COLUMN "status" SET DEFAULT 'pending'::"identity"."invitation_status";
ALTER TABLE "identity"."invitations" ALTER COLUMN "status" SET DATA TYPE "identity"."invitation_status" USING "status"::"identity"."invitation_status";
ALTER TABLE "finance"."accounts" ALTER COLUMN "account_type" SET DATA TYPE "finance"."account_type" USING "account_type"::"finance"."account_type";
ALTER TABLE "finance"."accounts" ALTER COLUMN "internal_type" SET DATA TYPE "finance"."account_internal_type" USING "internal_type"::"finance"."account_internal_type";
ALTER TABLE "system"."notifications" ALTER COLUMN "type" SET DATA TYPE "system"."notification_type" USING "type"::"system"."notification_type";
ALTER TABLE "system"."notifications" ALTER COLUMN "related_entity_type" SET DATA TYPE "system"."related_entity_type" USING "related_entity_type"::"system"."related_entity_type";
ALTER TABLE "identity"."appearance_settings" ALTER COLUMN "theme" SET DEFAULT 'light'::"identity"."theme";
ALTER TABLE "identity"."appearance_settings" ALTER COLUMN "theme" SET DATA TYPE "identity"."theme" USING "theme"::"identity"."theme";
ALTER TABLE "identity"."appearance_settings" ALTER COLUMN "color_scheme" SET DEFAULT 'blue'::"identity"."color_scheme";
ALTER TABLE "identity"."appearance_settings" ALTER COLUMN "color_scheme" SET DATA TYPE "identity"."color_scheme" USING "color_scheme"::"identity"."color_scheme";
ALTER TABLE "identity"."appearance_settings" ALTER COLUMN "font_size" SET DEFAULT 'medium'::"identity"."font_size";
ALTER TABLE "identity"."appearance_settings" ALTER COLUMN "font_size" SET DATA TYPE "identity"."font_size" USING "font_size"::"identity"."font_size";
ALTER TABLE "identity"."appearance_settings" ALTER COLUMN "density" SET DEFAULT 'comfortable'::"identity"."density";
ALTER TABLE "identity"."appearance_settings" ALTER COLUMN "density" SET DATA TYPE "identity"."density" USING "density"::"identity"."density";
ALTER TABLE "audit"."cases" ALTER COLUMN "audit_type" SET DATA TYPE "audit"."audit_type" USING "audit_type"::"audit"."audit_type";
ALTER TABLE "audit"."audit_templates" ALTER COLUMN "audit_type" SET DATA TYPE "audit"."audit_type" USING "audit_type"::"audit"."audit_type";
ALTER TABLE "audit"."audit_templates" ALTER COLUMN "category" SET DATA TYPE "audit"."audit_category" USING "category"::"audit"."audit_category";
ALTER TABLE "audit"."case_history" ALTER COLUMN "entity_type" SET DATA TYPE "audit"."case_entity_type" USING "entity_type"::"audit"."case_entity_type";
ALTER TABLE "audit"."case_history" ALTER COLUMN "action" SET DATA TYPE "audit"."case_action" USING "action"::"audit"."case_action";